/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatmp;

/**
 *
 * @author Mart
 */
public class DFAgui extends javax.swing.JFrame {

    /**
     * Creates new form DFAgui
     */
    public DFAgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Current = new javax.swing.JLabel();
        q1 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        q3 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        q6 = new javax.swing.JLabel();
        q7 = new javax.swing.JLabel();
        q8 = new javax.swing.JLabel();
        q9 = new javax.swing.JLabel();
        q10 = new javax.swing.JLabel();
        q11 = new javax.swing.JLabel();
        q12 = new javax.swing.JLabel();
        q13 = new javax.swing.JLabel();
        q14 = new javax.swing.JLabel();
        q15 = new javax.swing.JLabel();
        q16 = new javax.swing.JLabel();
        q17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SCurrent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Current.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/blue.PNG"))); // NOI18N
        getContentPane().add(Current);
        Current.setBounds(70, 330, 40, 40);

        q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q1);
        q1.setBounds(150, 100, 40, 40);

        q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q2);
        q2.setBounds(280, 200, 40, 40);

        q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q3);
        q3.setBounds(420, 200, 40, 40);

        q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q4);
        q4.setBounds(670, 10, 40, 40);

        q5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q5);
        q5.setBounds(490, 10, 40, 40);

        q6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q6);
        q6.setBounds(270, 330, 40, 40);

        q7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q7);
        q7.setBounds(420, 320, 40, 40);

        q8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q8);
        q8.setBounds(200, 520, 40, 40);

        q9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q9);
        q9.setBounds(20, 520, 40, 40);

        q10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q10);
        q10.setBounds(20, 20, 40, 40);

        q11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q11);
        q11.setBounds(270, 10, 40, 40);

        q12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q12);
        q12.setBounds(420, 10, 40, 40);

        q13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q13);
        q13.setBounds(270, 520, 40, 40);

        q14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q14);
        q14.setBounds(420, 520, 40, 40);

        q15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q15);
        q15.setBounds(650, 520, 40, 40);

        q16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/green.PNG"))); // NOI18N
        getContentPane().add(q16);
        q16.setBounds(610, 150, 40, 40);

        q17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/red.PNG"))); // NOI18N
        getContentPane().add(q17);
        q17.setBounds(530, 390, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatmp/automata.PNG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 720, 590);

        SCurrent.setText("Show Current");
        SCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCurrentActionPerformed(evt);
            }
        });
        getContentPane().add(SCurrent);
        SCurrent.setBounds(730, 60, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCurrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SCurrentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFAgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFAgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFAgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFAgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFAgui().setVisible(true);
            }
        });
    }
    public void showstep(int x){
        if(x==1){
            q1.setVisible(true);
        }else if(x==2){
            q2.setVisible(true);
        }else if(x==3){
            q3.setVisible(true);
        }else if(x==4){
            q4.setVisible(true);
        }else if(x==5){
            q5.setVisible(true);
        }else if(x==6){
            q6.setVisible(true);
        }else if(x==7){
            q7.setVisible(true);
        }else if(x==8){
            q8.setVisible(true);
        }else if(x==9){
            q9.setVisible(true);
        }else if(x==10){
            q10.setVisible(true);
        }else if(x==11){
            q11.setVisible(true);
        }else if(x==12){
            q12.setVisible(true);
        }else if(x==13){
            q13.setVisible(true);
        }else if(x==14){
            q14.setVisible(true);
        }else if(x==15){
            q15.setVisible(true);
        }else if(x==16){
            q16.setVisible(true);
        }else if(x==17){
            q17.setVisible(true);
        }else{
            Current.setLocation(70, 330);
        }
 
    }
    public void MoveCurrent(int x){
        if(x==1){
            Current.setLocation(q1.getX(), q1.getX());
        }else if(x==2){
            Current.setLocation(q2.getX(), q2.getX());
        }else if(x==3){
            Current.setLocation(q3.getX(), q3.getX());
        }else if(x==4){
            Current.setLocation(q4.getX(), q4.getX());
        }else if(x==5){
            Current.setLocation(q5.getX(), q5.getX());
        }else if(x==6){
            Current.setLocation(q6.getX(), q6.getX());
        }else if(x==7){
            Current.setLocation(q7.getX(), q7.getX());
        }else if(x==8){
            Current.setLocation(q8.getX(), q8.getX());
        }else if(x==9){
            Current.setLocation(q9.getX(), q9.getX());
        }else if(x==10){
            Current.setLocation(q10.getX(), q10.getX());
        }else if(x==11){
            Current.setLocation(q11.getX(), q11.getX());
        }else if(x==12){
            Current.setLocation(q12.getX(), q12.getX());
        }else if(x==13){
            Current.setLocation(q13.getX(), q13.getX());
        }else if(x==14){
            Current.setLocation(q14.getX(), q14.getX());
        }else if(x==15){
            Current.setLocation(q15.getX(), q15.getX());
        }else if(x==16){
            Current.setLocation(q16.getX(), q16.getX());
        }else if(x==17){
            Current.setLocation(q17.getX(), q17.getX());
        }else{
            Current.setLocation(70, 330);
        }
    }
    public void hideall(){
        q1.setVisible(false);
        q2.setVisible(false);
        q3.setVisible(false);
        q4.setVisible(false);
        q5.setVisible(false);
        q6.setVisible(false);
        q7.setVisible(false);
        q8.setVisible(false);
        q9.setVisible(false);
        q10.setVisible(false);
        q11.setVisible(false);
        q12.setVisible(false);
        q13.setVisible(false);
        q14.setVisible(false);
        q15.setVisible(false);
        q16.setVisible(false);
        q17.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Current;
    private javax.swing.JButton SCurrent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q11;
    private javax.swing.JLabel q12;
    private javax.swing.JLabel q13;
    private javax.swing.JLabel q14;
    private javax.swing.JLabel q15;
    private javax.swing.JLabel q16;
    private javax.swing.JLabel q17;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel q9;
    // End of variables declaration//GEN-END:variables
}
